


name: Generate Snake Game

on:

  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository content
        uses: actions/checkout@v2

      # Generate the snake game from the contributions graph
      - name: Generate snake game from contributions
        uses: Platane/snk@v2
        with:
          github_user_name: Deepeshgiri 
          gif_out_path: dist/github-contribution-grid-snake.gif

      # Upload the snake game GIF to the repository
      - name: Upload Snake Game GIF
        uses: actions/upload-artifact@v2
        with:
          name: snake-game
          path: dist/github-contribution-grid-snake.gif


